import {
  PatientProfile,
  Facility,
  DigitalReferral,
  EmergencyEvent,
  MedicalDocument,
  AccessAuditLog,
  UserSession,
} from '@/types';

export const SEED_USERS: UserSession[] = [
  {
    id: 'usr-patient-1',
    name: 'Ramesh Patel',
    role: 'PATIENT',
    mobile: '+91 98250 12345',
    email: 'ramesh.patel@example.com',
  },
  {
    id: 'usr-doctor-1',
    name: 'Dr. Priya Sharma',
    role: 'DOCTOR',
    mobile: '+91 98250 99881',
    email: 'dr.priya.sharma@phc.guj.gov.in',
    organizationId: 'fac-phc-1',
    organizationName: 'Anand Rural Community PHC',
  },
  {
    id: 'usr-hospital-doc-1',
    name: 'Dr. Rajesh Mehta',
    role: 'HOSPITAL_DOCTOR',
    mobile: '+91 98250 55443',
    email: 'dr.mehta@sterlingapex.org',
    organizationId: 'fac-hosp-1',
    organizationName: 'Sterling Apex Heart Institute',
  },
  {
    id: 'usr-hospital-admin-1',
    name: 'Amit Desai',
    role: 'HOSPITAL_ADMIN',
    mobile: '+91 98250 77665',
    email: 'admin@sterlingapex.org',
    organizationId: 'fac-hosp-1',
    organizationName: 'Sterling Apex Heart Institute',
  },
];

export const SEED_PATIENTS: PatientProfile[] = [
  {
    id: 'pat-1',
    userId: 'usr-patient-1',
    secureTokenId: 'PAT-1081-SEC',
    name: 'Ramesh Patel',
    age: 52,
    gender: 'MALE',
    mobile: '+91 98250 12345',
    location: 'Anand District, Gujarat',
    address: 'B-14, Shanti Nagar, Near Railway Station, Anand 388001',
    emergencyContact: {
      name: 'Kavita Patel',
      relationship: 'Spouse',
      phone: '+91 98250 12346',
    },
    bloodGroup: 'B+',
    weightKg: 74,
    existingConditions: ['Hypertension (diagnosed 2021)', 'Mild Hyperlipidemia'],
    allergies: ['Sulfa Drugs (Skin Rash)'],
    currentMedications: [
      { name: 'Amlodipine', dosage: '5mg', frequency: 'Once daily (morning)' },
      { name: 'Atorvastatin', dosage: '10mg', frequency: 'Once daily (night)' },
    ],
    medicalHistory: [
      {
        id: 'hist-1',
        condition: 'Essential Hypertension',
        diagnosedYear: '2021',
        status: 'ACTIVE',
        verifiedByDoctor: 'Dr. Priya Sharma',
        verifiedAt: '2025-11-10T10:30:00Z',
      },
      {
        id: 'hist-2',
        condition: 'Acute Gastroenteritis (Dehydration)',
        diagnosedYear: '2023',
        status: 'RESOLVED',
        verifiedByDoctor: 'Dr. Priya Sharma',
        verifiedAt: '2023-08-14T09:00:00Z',
      },
    ],
    consentGranted: true,
    createdAt: '2025-01-10T08:00:00Z',
  },
  {
    id: 'pat-2',
    userId: 'usr-patient-2',
    secureTokenId: 'PAT-2094-SEC',
    name: 'Priya Shah',
    age: 28,
    gender: 'FEMALE',
    mobile: '+91 98790 65432',
    location: 'Vadodara, Gujarat',
    address: '402, Nilkanth Heights, Gotri Road, Vadodara 390021',
    emergencyContact: {
      name: 'Nitin Shah',
      relationship: 'Brother',
      phone: '+91 98790 65433',
    },
    bloodGroup: 'O+',
    weightKg: 58,
    existingConditions: ['Bronchial Asthma (Moderate Persistent)'],
    allergies: ['PENICILLIN (SEVERE ANAPHYLAXIS RISK)'],
    currentMedications: [
      { name: 'Salbutamol Inhaler', dosage: '100mcg', frequency: 'As needed for wheezing' },
      { name: 'Budesonide Inhaler', dosage: '200mcg', frequency: 'Twice daily' },
    ],
    medicalHistory: [
      {
        id: 'hist-3',
        condition: 'Bronchial Asthma',
        diagnosedYear: '2018',
        status: 'ACTIVE',
        verifiedByDoctor: 'Dr. Priya Sharma',
        verifiedAt: '2025-02-12T11:00:00Z',
      },
    ],
    consentGranted: true,
    createdAt: '2025-02-01T08:00:00Z',
  },
  {
    id: 'pat-3',
    userId: 'usr-patient-3',
    secureTokenId: 'PAT-3382-SEC',
    name: 'Vikram Singh',
    age: 34,
    gender: 'MALE',
    mobile: '+91 99090 11223',
    location: 'Nadiad Highway, Gujarat',
    address: 'Village Uttarsanda, Nadiad Taluka 387370',
    emergencyContact: {
      name: 'Mahesh Singh',
      relationship: 'Father',
      phone: '+91 99090 11224',
    },
    bloodGroup: 'AB+',
    weightKg: 80,
    existingConditions: ['None known'],
    allergies: ['No Known Drug Allergies (NKDA)'],
    currentMedications: [],
    medicalHistory: [],
    consentGranted: true,
    createdAt: '2025-03-01T08:00:00Z',
  },
];

export const SEED_FACILITIES: Facility[] = [
  {
    id: 'fac-hosp-1',
    name: 'Sterling Apex Heart & Multi-Specialty Hospital',
    type: 'TERTIARY_CARE',
    location: 'Vadodara Central',
    address: 'Near Race Course Ring Road, Vadodara 390007',
    distanceKm: 12.4,
    travelTimeMins: 18,
    phone: '+91 265 233 4455',
    emergencyPhone: '+91 265 233 9999',
    capabilities: [
      'CARDIOLOGY',
      'CATH_LAB',
      'ECG',
      'EMERGENCY_24_7',
      'ICU',
      'NEUROLOGY',
      'DIAGNOSTIC_CT_MRI',
      'GENERAL_MEDICINE',
    ],
    isActive: true,
    demoNote: 'Tertiary referral center with 24/7 active interventional Cath Lab and dedicated Cardiac ICU.',
  },
  {
    id: 'fac-hosp-2',
    name: 'District Civil Hospital Anand',
    type: 'DISTRICT_HOSPITAL',
    location: 'Anand City',
    address: 'Civil Hospital Campus, Station Road, Anand 388001',
    distanceKm: 3.8,
    travelTimeMins: 8,
    phone: '+91 2692 250 123',
    emergencyPhone: '+91 2692 250 911',
    capabilities: [
      'EMERGENCY_24_7',
      'GENERAL_MEDICINE',
      'ECG',
      'ICU',
      'ORTHOPEDICS',
      'PEDIATRICS',
    ],
    isActive: true,
    demoNote: 'Equipped for general medical stabilization and emergency surgery, but lacks catheterization lab (Cath Lab).',
  },
  {
    id: 'fac-hosp-3',
    name: 'Lifeline Trauma, Ortho & Emergency Care',
    type: 'SPECIALTY_TRAUMA',
    location: 'V.V. Nagar Highway',
    address: 'GIDC Industrial Corridor, V.V. Nagar 388120',
    distanceKm: 6.5,
    travelTimeMins: 11,
    phone: '+91 2692 245 888',
    emergencyPhone: '+91 2692 245 999',
    capabilities: [
      'TRAUMA_CARE',
      'ORTHOPEDICS',
      'EMERGENCY_24_7',
      'DIAGNOSTIC_CT_MRI',
      'ICU',
      'GENERAL_MEDICINE',
    ],
    isActive: true,
    demoNote: 'Level-2 Trauma and orthopedic center with 24/7 helical CT scanner and surgical theater.',
  },
  {
    id: 'fac-phc-1',
    name: 'Anand Rural Community PHC',
    type: 'COMMUNITY_PHC',
    location: 'Anand Rural Sector 3',
    address: 'Primary Health Centre Campus, Anand Rural 388002',
    distanceKm: 1.5,
    travelTimeMins: 4,
    phone: '+91 2692 221 004',
    emergencyPhone: '+91 2692 221 108',
    capabilities: ['GENERAL_MEDICINE', 'ECG'],
    isActive: true,
    demoNote: 'Primary outpatient point of care; performs initial triage and transfers to higher facilities.',
  },
];

export const SEED_REFERRALS: DigitalReferral[] = [
  {
    id: 'ref-1',
    referralCode: 'REF-2026-0412',
    secureQrToken: 'SIG_REF_0412_a8b9c2d1',
    patientId: 'pat-1',
    patientSnapshot: {
      name: 'Ramesh Patel',
      age: 52,
      gender: 'MALE',
      mobile: '+91 98250 12345',
      bloodGroup: 'B+',
      allergies: ['Sulfa Drugs (Skin Rash)'],
      medications: [{ name: 'Amlodipine', dosage: '5mg' }],
      conditions: ['Hypertension'],
    },
    referringDoctorId: 'usr-doctor-1',
    referringDoctorName: 'Dr. Priya Sharma (MBBS, MO)',
    referringClinic: 'Anand Rural Community PHC',
    receivingFacilityId: 'fac-hosp-1',
    receivingFacilityName: 'Sterling Apex Heart & Multi-Specialty Hospital',
    urgency: 'URGENT',
    chiefComplaint: 'Substernal chest heaviness radiating to left shoulder on exertion',
    duration: 'Started 2 hours ago during morning walk',
    clinicalFindings: 'Patient visibly diaphoretic. BP 154/96 mmHg, Pulse 92 bpm regular, SpO2 97% on room air. PHC 12-Lead ECG shows ST depression in leads V4-V6.',
    vitals: {
      bloodPressure: '154/96',
      heartRate: 92,
      spo2: 97,
      temperatureF: 98.4,
      bloodGlucose: 142,
    },
    careRequirement: 'Emergency Cardiology Consultation & Urgent Coronary Angiography (Cath Lab)',
    requiredCapabilities: ['CARDIOLOGY', 'CATH_LAB', 'ECG', 'EMERGENCY_24_7', 'ICU'],
    aiAssessmentSummary: 'AI Triage suggested urgent tertiary cardiology evaluation due to exertional angina with ECG ST-T wave changes.',
    doctorConfirmedDecision: 'Confirmed by Dr. Priya Sharma. Clinical findings consistent with Acute Coronary Syndrome (NSTEMI suspected). Immediate tertiary transfer required.',
    isDoctorOverridden: false,
    status: 'ACCEPTED',
    events: [
      {
        id: 'ev-1',
        referralId: 'ref-1',
        status: 'CONFIRMED',
        actorRole: 'DOCTOR',
        actorName: 'Dr. Priya Sharma',
        timestamp: '2026-09-18T18:40:00Z',
        notes: 'Clinical referral created and signed at PHC.',
      },
      {
        id: 'ev-2',
        referralId: 'ref-1',
        status: 'SENT',
        actorRole: 'DOCTOR',
        actorName: 'Dr. Priya Sharma',
        timestamp: '2026-09-18T18:41:00Z',
        notes: 'Transmitted securely to Sterling Apex Heart Institute dashboard.',
      },
      {
        id: 'ev-3',
        referralId: 'ref-1',
        status: 'ACCEPTED',
        actorRole: 'HOSPITAL_DOCTOR',
        actorName: 'Dr. Rajesh Mehta',
        timestamp: '2026-09-18T18:45:00Z',
        notes: 'Referral accepted. Cath Lab team on standby; Cardiac ICU Bed #4 reserved.',
      },
    ],
    createdAt: '2026-09-18T18:40:00Z',
    updatedAt: '2026-09-18T18:45:00Z',
  },
];

export const SEED_EMERGENCY_EVENTS: EmergencyEvent[] = [
  {
    id: 'sos-1',
    patientId: 'pat-1',
    patientName: 'Ramesh Patel',
    patientAge: 52,
    patientGender: 'MALE',
    bloodGroup: 'B+',
    allergies: ['Sulfa Drugs (Skin Rash)'],
    currentMedications: ['Amlodipine 5mg', 'Atorvastatin 10mg'],
    existingConditions: ['Hypertension (2021)'],
    ambulanceId: 'AMB-GJ-01-1082',
    ambulanceStatus: 'EN_ROUTE',
    etaMinutes: 6,
    emergencySymptoms: [
      'Crushing central chest pain (severity 9/10)',
      'Severe breathlessness & cold sweats',
      'Onset 25 minutes ago',
    ],
    emergencyNotes: 'Parallel emergency AI assistant captured acute onset radiating pain. Patient conscious but distressed.',
    careRequirement: 'Immediate Advanced Cardiac Life Support (ACLS) & Emergent Cath Lab Access',
    requiredCapabilities: ['CARDIOLOGY', 'CATH_LAB', 'EMERGENCY_24_7', 'ICU'],
    selectedFacilityId: 'fac-hosp-1',
    selectedFacilityName: 'Sterling Apex Heart & Multi-Specialty Hospital',
    hospitalStatus: 'ACCEPTED',
    timeline: [
      {
        time: '18:50:10',
        label: 'SOS Button Triggered',
        detail: 'Patient triggered Emergency Fast-Lane from mobile device.',
      },
      {
        time: '18:50:11',
        label: '108 Ambulance Action Initiated',
        detail: 'Automatic 108 dispatch broadcast triggered. Vehicle AMB-GJ-01-1082 assigned.',
      },
      {
        time: '18:50:45',
        label: 'Parallel Clinical Context Aggregated',
        detail: 'Patient profile (Hypertension, B+, Sulfa allergy) fused with acute symptoms.',
      },
      {
        time: '18:51:15',
        label: 'Destination Facility Selected',
        detail: 'Sterling Apex Heart Institute selected based on 24/7 Cath Lab requirement.',
      },
      {
        time: '18:51:30',
        label: 'Hospital Triage Alerted',
        detail: 'High-priority audio/visual alert received on Hospital Emergency HUD.',
      },
      {
        time: '18:52:00',
        label: 'Hospital Accepted & Mobilized Team',
        detail: 'Dr. Rajesh Mehta accepted. Trauma/Cath Lab bay prepared.',
      },
    ],
    createdAt: '2026-09-18T18:50:10Z',
  },
];

export const SEED_DOCUMENTS: MedicalDocument[] = [
  {
    id: 'doc-1',
    patientId: 'pat-1',
    title: 'Discharge Summary & ECG Report (Readable Demo)',
    fileType: 'PDF',
    uploadedAt: '2026-09-10T11:20:00Z',
    isReadable: true,
    rawTextPreview: 'STERLING HOSPITAL DISCHARGE NOTE\nPatient: Ramesh Patel (52M)\nDiagnosis: Essential Systemic Hypertension\nRecorded BP: 150/90 mmHg\nAdvised Rx: Tab Amlodipine 5mg OD\nECG: Normal Sinus Rhythm, Left Axis Deviation.',
    candidateExtraction: {
      conditions: ['Essential Systemic Hypertension'],
      medications: ['Tab Amlodipine 5mg Once Daily'],
      vitals: {
        bloodPressure: '150/90 mmHg',
        pulseRate: '78 bpm',
      },
      notes: 'Readable digital discharge summary. Clear diagnostic formulation.',
      confidence: 0.94,
    },
    verificationStatus: 'VERIFIED',
    verifiedByDoctorName: 'Dr. Priya Sharma',
    verifiedAt: '2026-09-10T12:00:00Z',
  },
  {
    id: 'doc-2',
    patientId: 'pat-1',
    title: 'Comprehensive Metabolic & Lipid Panel (Readable Demo)',
    fileType: 'PDF',
    uploadedAt: '2026-09-17T09:15:00Z',
    isReadable: true,
    rawTextPreview: 'METROPOLIS LABS REPORT\nTest: HbA1c: 6.1% (Prediabetic range)\nFasting Blood Sugar: 112 mg/dL\nTotal Cholesterol: 218 mg/dL\nSerum Creatinine: 0.95 mg/dL',
    candidateExtraction: {
      conditions: ['Mild Hyperlipidemia', 'Prediabetes (Impaired Fasting Glucose)'],
      medications: ['Atorvastatin 10mg'],
      vitals: {
        fastingGlucose: '112 mg/dL',
        hba1c: '6.1%',
      },
      notes: 'Standard diagnostic blood panel.',
      confidence: 0.92,
    },
    verificationStatus: 'NEEDS_VERIFICATION',
  },
  {
    id: 'doc-3',
    patientId: 'pat-1',
    title: 'Blurry Handwritten OPD Slip (Unreadable Fallback Demo)',
    fileType: 'IMAGE_JPG',
    uploadedAt: '2026-09-18T14:00:00Z',
    isReadable: false,
    rawTextPreview: '<< Heavily degraded handwriting / low resolution scan >>',
    candidateExtraction: undefined,
    verificationStatus: 'NEEDS_VERIFICATION',
  },
];

export const SEED_AUDIT_LOGS: AccessAuditLog[] = [
  {
    id: 'aud-1',
    userId: 'usr-doctor-1',
    userName: 'Dr. Priya Sharma',
    userRole: 'DOCTOR',
    patientId: 'pat-1',
    patientName: 'Ramesh Patel',
    action: 'PATIENT_LOOKUP',
    contextReason: 'Routine PHC OPD consultation with patient consent',
    isBreakGlass: false,
    timestamp: '2026-09-18T18:35:00Z',
  },
  {
    id: 'aud-2',
    userId: 'usr-doctor-1',
    userName: 'Dr. Priya Sharma',
    userRole: 'DOCTOR',
    patientId: 'pat-1',
    patientName: 'Ramesh Patel',
    action: 'REFERRAL_CREATE',
    contextReason: 'Exertional angina with ST depression. Urgent cardiology referral.',
    isBreakGlass: false,
    timestamp: '2026-09-18T18:40:00Z',
  },
  {
    id: 'aud-3',
    userId: 'usr-hospital-doc-1',
    userName: 'Dr. Rajesh Mehta',
    userRole: 'HOSPITAL_DOCTOR',
    patientId: 'pat-1',
    patientName: 'Ramesh Patel',
    action: 'EMERGENCY_BREAK_GLASS',
    contextReason: 'Active Emergency SOS triggered. ACLS preparation and Cath Lab pre-activation.',
    isBreakGlass: true,
    timestamp: '2026-09-18T18:51:35Z',
  },
];
